---
title: Freelancer
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: SachiSaori@yandex.ru
url: https://sachisaori.github.io
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
keywords: your keywords, separated by commas
skills: Web Developer - Android developer - iOS developer
meta_author: Sofia Levakova
google_verify: 
bing_verify: 
contact: static
disqus_shortname: myshortname
color:
  primary: 18bc9c
  primary-rgb: '24,288,156'
  secondary: 2c3e50
  secondary-dark: 233140
footer:
  copyright: Sofia Levakova
  location: Location
  social: Around the Web
  credits: Credits
social:
- title: twitter
  url: https://twitter.com/SachiSaori
- title: github
  url: https://github.com/SachiSaori
- title: vk
  url: https://vk.com/id403032055
address:
- line: 
- line: 
credits: 'This site working on Jekyll. Hosted by Github Pages'
markdown: kramdown
permalink: pretty
